version: '3'
services:
        database:
                image: postgres
                environment:
                        - POSTGRES_USER=dsi
                        - POSTGRES_PASSWORD=dsi
                ports:
                        - "5432:5432"
