#!/bin/bash

set -e

DSI_HOME_BIN="/opt/dsi/runtime/ia/bin"

if [ -z "$JAVA_HOME" ]; then
        export JAVA_HOME=/opt/dsi/jdk/jre
fi

echo "JAVA_HOME=$JAVA_HOME" > /opt/dsi/runtime/wlp/etc/server.env

$DSI_HOME_BIN/$1 ${@:2}
