version: '3'
services:
        dsi-runtime-catalog:
                container_name: dsi-runtime-catalog
                image: $DSI_IMAGE
                command: ["/root/start.sh", "dsi-runtime-catalog"]
                ports:
                        - 2809:2809

        dsi-runtime:
                image: $DSI_IMAGE
                command: ["/root/start.sh", "dsi-runtime-container", "dsi-runtime-catalog"]
                depends_on:
                        - dsi-runtime-catalog
                ports:
                        - 9443
                environment:
                        - TCP_PORTS=9443

        dsi-runtime-inbound:
                image: $DSI_IMAGE
                command: ["/root/start.sh", "dsi-runtime-inbound", "dsi-runtime-catalog", "wait_for_grid_availability"]
                ports:
                        - 9444
                        - 9081
                environment:
                        - TCP_PORTS=9444,9081
                depends_on:
                        - dsi-runtime-catalog
                        - dsi-runtime

        dsi-runtime-outbound:
                container_name: dsi-runtime-outbound
                image: $DSI_IMAGE
                command: ["/root/start.sh", "dsi-runtime-outbound", "dsi-runtime-catalog", "wait_for_grid_availability"]
                ports:
                        - 9082
                        - 9445
                environment:
                        - TCP_PORTS=9445,9082
                depends_on:
                        - dsi-runtime-catalog
                        - dsi-runtime

        lb:
                image: dockercloud/haproxy
                links:
                        - dsi-runtime
                        - dsi-runtime-inbound
                        - dsi-runtime-outbound
                environment:
                        - BALANCE=roundrobin
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                ports:
                        - $HTTPS_RUNTIME:9443
                        - $HTTPS_INBOUND:9444
                        - $HTTP_INBOUND:9081
                        - $HTTPS_OUTBOUND:9445
                        - $HTTP_OUTBOUND:9082
                depends_on:
                        - dsi-runtime-catalog
                        - dsi-runtime
